name: flutter_application_pa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  image_picker: ^1.1.2
  firebase_storage: ^12.3.5
  # image_picker: ^1.1.2
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  flutter_secure_storage: ^7.0.0
  flutter:
    sdk: flutter
  

  
  introduction_screen: ^3.1.14
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  # image_picker: ^0.8.5+3
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/ikon.png" 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/hama_padi/
    - assets/jenis_padi/
    - assets/nutrisi/
    - assets/penyakit/
    - assets/solusi/
    - assets/avatar1.png
    - assets/avatar2.png
    - assets/avatar3.png
    - assets/avatar4.png

