// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYho9Nn3kUx-bZEkBTedqn4VbZmfoLkr8',
    appId: '1:783506516310:web:ca37712265f5fd1a744ef7',
    messagingSenderId: '783506516310',
    projectId: 'padi-sakit',
    authDomain: 'padi-sakit.firebaseapp.com',
    storageBucket: 'padi-sakit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsVupUqprspVaqXLmiXUGXMdnyiw5oDDI',
    appId: '1:783506516310:android:9badc3fe65550b8e744ef7',
    messagingSenderId: '783506516310',
    projectId: 'padi-sakit',
    storageBucket: 'padi-sakit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbGrhqPZFTuppLmUdGuLfHV7xZ35dFVJc',
    appId: '1:783506516310:ios:ab05c0b97bb8a5f0744ef7',
    messagingSenderId: '783506516310',
    projectId: 'padi-sakit',
    storageBucket: 'padi-sakit.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationPa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbGrhqPZFTuppLmUdGuLfHV7xZ35dFVJc',
    appId: '1:783506516310:ios:ab05c0b97bb8a5f0744ef7',
    messagingSenderId: '783506516310',
    projectId: 'padi-sakit',
    storageBucket: 'padi-sakit.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationPa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYho9Nn3kUx-bZEkBTedqn4VbZmfoLkr8',
    appId: '1:783506516310:web:5c0f7b6ab38421bd744ef7',
    messagingSenderId: '783506516310',
    projectId: 'padi-sakit',
    authDomain: 'padi-sakit.firebaseapp.com',
    storageBucket: 'padi-sakit.firebasestorage.app',
  );

}